---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: squad01
  namespace: squad01
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/victorhgarciay/squad01

